### ISSUE TITLE
Улучшение get_info()

### ISSUE THREAD

**Issue by Suor** [dariyagrishina/kind-of-graduation-project#10]
Многими способами:
- [x] перейти на более надёжный граббинг по атрибуту `itemprop`
- [x] спроектировать API функции (написать проект сюда)
- [x] реализовать новое API 
- [x] использовать регулярные выражения, где следует
- [x] написать тесты

**Comment by Suor** [comment]
Про тесты. Есть много способов их писать, самый простой - создаём файл `tests.py` и пишем туда:

``` python
from lib import get_info

def test_get_info():
    matrix = get_info(13)
    assert matrix['title'] == u'Матрица'
    assert matrix['year'] == 1999
    ...

    other_film = get_info(...)
    assert ...
    ...

test_get_info()
```

Запускаешь тесты с помощью команды `python tests.py` и получаешь что там да как. Не нужно ничего смотреть и сравнивать.

**Comment by dariyagrishina** [comment]
Есть вопросы.
Вернуть то, что функция успела сделать - это я могу, пожалуй. Выкинуть исключение - может быть, я представляю что читать и делать.
А как спроектировать API функции? Как реализовать?
Я спросила у гугла, но ничего не поняла. Задавала вопрос "creating an api in python". Вот, например, ссылка из первого источника http://flask.pocoo.org/extensions/ Это вообще то или не то?

**Comment by dariyagrishina** [comment]
Тьфу, вот ссылка. http://www.fullstackpython.com/api-creation.html

**Comment by Suor** [comment]
Там говорится про API для сервиса, а тут API для функции. 

API = Application programming interface. Т.е. интерфейс для программ/программистов - то как твоей функцией пользоваться. Состоит из:
- имени,
- аргументов (количество, порядок, имена, типы),
- возвращаемого значения (тип),
- семантики, т.е. описания того, что функция делает,
- семантики исключительных ситуаций. Например, что функция будет делать если не найдёт одно из полей? Что она будет делать если не сможет загрузить страницу? и т.п.

В данном случае значительная часть - это возвращемое значение. Нужно описать его структуру, типы всех составных частей.

**Comment by Suor** [comment]
Если всё ещё страшно и непонятно как писать API функции, то напиши несколько примеров.

**Comment by dariyagrishina** [comment]
Не страшно мне (ну разве что немного), времени у меня нет :(

**Comment by dariyagrishina** [comment]
API
1) Функция get_info(movie_id).
Тип аргумента - integer.
Возвращаемое значение - словарь.
Функция присваивает строку - html страницы filmz.ru c вышеуказанным id фильма (аргумент функции) переменной page_content.
Далее создается instance soup с использованием библиотеки BeautifulSoup.
Функция возвращает словарь, в котором имеются следующие пары: 1) key - это строка "title", а value - возвращенное вспомогательной функцией _get_title(soup) название фильма по заданному в аргументе get_info movie_id в unicode, взятое из html загруженной страницы; 2) key - это строка "year", value - возвращенное вспомогательной функцией _get_year(soup) год производства фильма по заданному в аргументе get_info movie_id, integer; 3) key - это строка "description", value - возвращенное вспомогательной функцей _get_description(soup) описание фильма по заданному в аргументе get_info movie_id в unicode. 4) key - это строка "duration", value - возвращенное вспомогательной функцией _get_duration(soup) длительность фильма по заданному в аргументе get_info movie_id, integer. 5) key - это строка "genre", value - возвращенное вспомогательной функцией _get_genre жанр фильма по заданному в аргументе get_info movie_id в unicode. 
Семантика исключительных ситуаций. В случае, если функция не сможет загрузить страницу, будет ошибка IOError: [Errno socket error] [Errno -2].

**Comment by Suor** [comment]
Хе-хе. Ревью твоего проекта:
1. Он плохо структурирован. Начинается с 1), для которого нет 2). Внутри идут ещё 1), 2), ... не разбитые по строкам. Не сделана разбивка по абзацам. Не `выделен код`. Почитай как использовать markdown в комментариях. Можешь ещё понажимать иконку "редактировать" рядом с моими, чтобы понять что я в них пишу, чтобы добиться красоты :).
2. По аргументам. Не указано количество (один), в питоне нет типа `integer`, есть `int`. Не описано, что значит аргумент.
3. Описание возвращаемого значения разбито, сначала сказано, что она возвращает словарь, потом идёт описание внутренностей функции, потом описание словаря.
4. Значения в возвращаемом словаре описаны в терминах реализации, например: "key - это строка `"title"`, а value - возвращенное вспомогательной функцией `_get_title(soup)` название фильма по заданному в аргументе `get_info` `movie_id` в `unicode`, взятое из html загруженной страницы;". О, боже! Вместо этого они должны быть описаны в терминах задачи, например: "по ключу `"title"` находится название фильма". В конце можно добавить, что все строки идут как `unicode`.
5. Вместо семантики функции описана реализация. 
6. Исключительные ситуации включают в себя не только выбрасывание исключений, но и ситуации обработанные на месте. Например: "если не удаётся найти продолжительность фильма, то в поле `duration` возвращается `None`".
7. Описано текущее поведение функции вместо проектирования того, как она должна работать в идеале, что является существенной частью задачи проектирования.

Кажется, вот этот момент не до конца ясен. API - интерфейс функции для программиста, т.е. инструкция как ей пользоваться. Внутреннее устройство в инструкцию не включается, и может теоретически в будущем менятся без изменения использующего её кода. Это один из смыслов API - скрытие информации, т.е. тебе не нужно знать как функция устроена, чтобы использовать её, не нужно думать об этом, не нужно помнить. Очень полезное свойство, т.к. количество вещей, о которых человек может думать одновременно ограничено. Кое-кто даже считает, что всё искусство программирования - это искусство прятать реализацию.

Теперь ты понимаешь почему это задание так важно? Не расстраивайся, что с первого раза у тебя не получилось чёткое описание API. Это нормально, и, кстати, многие программисты уже работающие в отрасли нихрена не умеют это делать ).

**Comment by Suor** [comment]
Думаю, для закрепления стоит сделать попытку номер 2.

**Comment by dariyagrishina** [comment]
get_info() находит и возвращает информацию о фильме с сайта filmz.ru:

``` python
>>> get_info(13)
{
    "title": u"Матрица",
    "year": 1998,
    "description": u"...",
    "genres": [u"фантастика", u"приключенческий"],
    "duration": 122
}
```

Аргумент `get_info()` - идентификатор фильма на filmz.ru.
Возвращаемое значение - словарь с ключами как в примере.

Если название, год, описание или продолжительность не будут найдены,
то в соответствующих полях будет `None`.
Если жанры не будут найдены, то в соответствующем поле будет `[]`.
Если функция не может найти страницу, то она выбрасывает IOError.

**Comment by dariyagrishina** [comment]
Вроде все сделала. Код, к моему сожалению, усложнился, но вроде читабелен.

**Comment by Suor** [comment]
Кроме того, что в коде:
- не везде перейдено на `itemprop`,
- тесты не удалось запустить из-за того, что не установлен прекрасный суп. Нужно добавить его в `requirements.txt`,
- можно добавить в README секцию "Testing",
- в этот же коммит попали изменения с `index.html` - нехорошо.

**Comment by Suor** [comment]
Дебрифинг.

На этот раз пришлось работать с существенным куском кода, превышающим одну небольшую функцию. Более того, тебе удалось вкусить разные аспекты разработки: проектирование, реализацию, отладку и тестирование. Также, т.к. было несколько одновременных заданий и эта задача была разбита на части, то всплыл вопрос приоритетов.

В целом это уже похоже на кусочек настоящей работы, который был преодолён :) Молодец.

Новые понятия:
- приоритеты
- проектирование API функции
- тестирование
- обработка ошибок
- выборки по CSS-селекторам
- регулярные выражения
- неявный возврат None

Старые вещи, которым следует уделить больше внимания:
- сравнение с уникальными объектами (is None)

Про приоритеты я напишу отдельно. Насчёт обработки ошибок - мы использовали 3 стратегии: переход на запасной вариант, выдача значения по умолчанию и пассивное позволение всплыть исключению (`IOError` из `get_page()`). Тестирование было не просто, а с помощью фреймворка pytest.

Также посмотри изменения, которые я внёс [здесь](https://github.com/dariyagrishina/kind-of-graduation-project/commits/master) (последние 3 коммита).

**Comment by Suor** [comment]
Приоритеты.

В целом приоритезация сводится к правилу:

> Первой делай наиболее определяющую часть.

Под наиболее определяющей здесь имеется в виду часть, которая максимально влияет на разработку проекта в целом. Признаками наиболее определяющей части являются:
- неясно можно ли вообще её сделать
- неясно как её делать
- нельзя делать что-то другое пока это не сделано
- без этой части ничего полезного продукт делать не может
- это ключевая функциональность продукта

Первые 2 аспекта, "неясно ...", могут быть пугающими, поэтому такие вещи часто откладываются, что здорово вредит проекту. Т.к. если ключевую вещь сделать вообще нельзя, то следует переосмыслить проект или забросить его, а не тратить время на реализацию второстепенного функционала, который потом может не пригодится. Если делать вещь неясно как, то её реализация может повлиять как нужно делать остальные части продукта и поэтому когда мы откладываем такую вещь, то что-то скорее всего придётся переделывать.

Остальные признаки не так сильны, но тем не менее позволяют быстрее и лучше завершить проект. Или если проект не будет завершён (цель изменилась, время/деньги кончились), то выдают максимально практически полезную его часть.

Применимо к текущей задаче, самая определяющая часть была "спроектировать API функции", т.к. остальные пункты от этого неявно зависят, а "реализовать API" зависит явно. Кроме того, сама задача про `get_info()` - ключевая для сервиса, т.к. он не будет работать без данных о фильмах. Для сравнения без html-странички приложение всё же может работать как утилита коммандной строки.
