### ISSUE TITLE
Поиск в "базе"

### ISSUE THREAD

**Issue by Suor** [dariyagrishina/kind-of-graduation-project#17]
Нужно написать функцию поиска фильмов по имеющейся базе (имеется в виду JSON-файл). Функция должна принимать поисковую фразу и возвращать список фильмов, в любых полях каждого их которых содержаться все искомые слова.

**Comment by Suor** [comment]
Я написал тесты для твоего кода - https://github.com/dariyagrishina/kind-of-graduation-project/commit/41f0ca02f1c15e21465a15176dbccfc54208e21d. На данный момент они валятся по двум причинам:
- `_search_item_matches()` и `_movie_matches()` ожидают поисковую штуку в виде бинарной строки, что неправильно. Внутренние функции всегда должны работать с юникодом. Тесты передают юникодные строки и поэтому всё валится.
-  неправильно организован разбор поисковой фразы на слова, например если искать "Нео, должен", то фраза будет разбита на "Нео," и "должен" и первый токен найден не будет, т.к. при разбивке текста запятая корректно отбрасывается.

Чтобы подготовится к рефакторингу, поправь код так, чтобы тесты заработали. Полноценное ревью последует после этого.

Примечание: в `test_db.py` я использую

``` python
from __future__ import unicode_literals
```

чтобы не ставить `u` перед каждой строкой, это заклинание делает все строки юникодными по-умолчанию.

**Comment by dariyagrishina** [comment]
Сделано.

**Comment by Suor** [comment]
Ещё один момент, который я забыл упомянуть в ревью - функция поиска должна возвращать всю инфу о фильмах, не только название, а то дальше нельзя будет, например, отобразить список найденных фильмов на странице.

**Comment by Suor** [comment]
Дебрифинг.

Задание, которое казалось в начале лёгким, оказалось, скажем так, весьма существенным. Можно также назвать его большим заданием на повторение. Возможно, в больших масштабах, но нужно было грамотно применить следующие уже знакомые тебе вещи:
- разбиение кода на функции,
- именование переменных и функций,
- тесты,
- юникод и бинарный текст,
- регулярные выражения.

Думаю, ещё одной существенной частью задачи стала разработка пусть и несложного, но алгоритма поиска. В первой версии, если помнишь, ты даже использовала счётчики совпадений. Что было хоть и неоптимальным, и даже ошибочным, но тем не менее рабочим решением. Это было круто, молодец.

Некоторые новые штуки:
- docstring
- укороченая схема выполнения or (short-circuit)
- рефакторинг - правка рабочего кода, к тому же покрытого тестами.

Ещё пара вещей, которые были упущены и напомнены:
- конкатенация с помощью `''.join()`,
- слишком длинные строки.

В качестве завершающих штрихов я: перенёс `human_readable()` в `utils` и снабдил его docstring-ом, альтернатива - удалить его, т.к. больше не используется; переформулировал docstring для `_parse()`.
