### ISSUE TITLE
Получить название фильма

### ISSUE THREAD

**Issue by Suor** [dariyagrishina/kind-of-graduation-project#2]
Новая программа должна по id фильма на [kinopoisk.ru](http://www.kinopoisk.ru) выдавать его название. id содержится в URL, например для `http://www.kinopoisk.ru/film/432/` id = 432.

Используется так:

``` bash
$ python get_title.py 301
Матрица
```

**Comment by dariyagrishina** [comment]
Начата функция get_title. Не решены проблемы:
1) не уверена, что выходящий title и есть title;
2) не оформлен ввод номера фильма с командной строки;
3) стоит вопрос с кодировкой.
Имеющееся запушено :)

**Comment by dariyagrishina** [comment]
Нет, не могу молчать!
На самом деле я искала title после вот этого <h1 class="moviename-big" itemprop="name">Чёрное море</h1>, но он показывал ошибку и я сдалась, решив, что сегодня не мой день.

**Comment by Suor** [comment]
Когда ты видишь странные символы или кракозябры, то проблема, как правило, с кодировками. Поэтому пришло время тебе узнать что это такое. О них в контексте питона можно почитать [здесь](http://www.py-my.ru/post/4bfb3c6a1d41c846bc00009b) (более практично, но не совсем точно) и [здесь](http://habrahabr.ru/post/135913/) (более корректно).

Подсказка после того как ты всё прочитаешь. kinopoisk выдаёт текст в кодировке cp1251 (ретрограды), а линуксовая консоль ожидает utf-8, поэтому ты видишь значки "нет такого символа". Смешно, что в винде это могло сработать, хе-хе, т.к. cp1251 - виндовая кодировка.

**Comment by dariyagrishina** [comment]
Не все, что хотела, сделала, но что сделано - можно уже смотреть :)

**Comment by Suor** [comment]
Как видишь отревьюил, kinopoisk заменяем на filmz.ru:

``` bash
$ python get_title.py 13
Матрица
```

**Comment by Suor** [comment]
Круто, название достаётся. Молодец.

Замечания:
1. `python get_title.py 13` не работает, т.к. нет файла `get_title.py`.
2. `get_page.py` похоже был сломан, теперь он не выдаёт страницу как раньше. Переоткрываю #1.
3. `python get_page.py hahaha` выдаёт какой-то кусок html.
4. `python get_page.py` просит передать ему `page-url`, но принимает id.

**Comment by Suor** [comment]
Дебрифинг.

Задача оказалась не такой простой, какой казалась по началу. Добро пожаловать в клуб :)

Старые идеи, которые были поддержаны (молодец!):
- одна функция - одна цель,
- соглашения по пробельным символам.

Старые идеи, которые были упущены (будь внимательнее):
- проверка входных параметров

Новые идеи и понятия:
- кодировки строк,
- логические и бинарные строки,
- отделение ввода/вывода от остальной части программы,
- использование нового имени для новой вещи,
- тест на тип (`isinstance`, `type`) против теста на содержимое.

Ещё один общий момент - сообщения коммитов принято писать с большой буквы.
