### ISSUE TITLE
Кешировать запрос страницы

### ISSUE THREAD

**Issue by Suor** [dariyagrishina/kind-of-graduation-project#6]
Чтобы каждый раз не дёргать сайт и быстрее отлаживать код нужно модифицировать приложение таким образом, чтобы ранее запрошенные страницы сохранялись. Сохранять нужно в файлы, чтобы кеш работал между запусками программы. 

Подсказка: т.к. файл не может иметь в своём имени все те символы, что встречаются в URL, то URL придётся как-то кодировать.

**Comment by dariyagrishina** [comment]
Задача выполнена для одного url, подаваемого с командной строки.
Изучены функции .write(), .read(), ord(). Пришлось повозиться, но я очень довольна.

**Comment by Suor** [comment]
Кроме того, что в ревью нужно:
- удалить файлы из `contents/`,
- придумать название для директории получше,
- добавить директорию в репозиторий,
- добавить содержимое директории в игнорируемые файлы, чтобы они в репозиторий не попадали. См. `.gitignore`.

**Comment by dariyagrishina** [comment]
Пишут, что "Git doesn't track folders, only files", и что в таком случае можно создать файл, назвать его .gitignore и кое-что написать в нем. Посмотри, верно ли я все сделала)

**Comment by Suor** [comment]
`.gitignore` должен быть только один, тот который уже лежит в корне репозитория. Игноры нужно добавлять в него. Если ты хочешь игнорировать все файлы в директории, то строка игнора должна выглядеть как:

```
dir_name/*
```

**Comment by dariyagrishina** [comment]
Корень репозитория - это основная папка? Что такое строка игнора? Ничего не понимаю :(  Мне нужно создать файл, назвать его .gitignore, и написать в нем cached_pages/*?
Посмотри, пожалуйста, остальное, что я наисправляла.

**Comment by Suor** [comment]
Корень - основная папка, там где лежит README. Файл `.gitignore` там уже лежит, нужно просто дописать в него строку. Строка игнора - строка в файле `.gitignore`.

**Comment by Suor** [comment]
Я посмотрел про пустые директории. Я тебе соврал ) Их нельзя добавить в git. И трюк с файлом, чтобы добавить директорию в общем нормальный. Кроме того, несколько `.gitignore` файлов вполне работают, каждый относительно директории, в которой лежит. Просто обычно так не делают.

Хе-хе :) Нужно отстаивать своё мнение. Так что добавляешь файл, например `.keep` как предлагают на той страничке StackOverflow и в шоколаде.

**Comment by Suor** [comment]
Кстати, в текущей реализации кеширования баг. `os.path.isfile()` ищет файл в текущей директории и никогда его не найдёт, а пожтому весь кеш не работает. Кстати, баг является результатом дублирования, которое тоже надо устранить.

**Comment by Suor** [comment]
А ещё `cached_page` - очень странное название для переменной файла. Люди будут ожидать, что там строка или объект страницы, а не файл.

**Comment by dariyagrishina** [comment]
Только сейчас увидела твой комментарий про пустые директории. Да, надо тебя уже не бояться и отстаивать свою точку зрения )

**Comment by dariyagrishina** [comment]
Замечания исправила, можешь посмотреть.

**Comment by Suor** [comment]
Итак кеширование готово, файлы побеждены, пути раскурены и Даша торжествует. На этот раз пришлось разработать небольшой алгоритм, и пусть он был не лучшим из возможных, но он работал.

Старые вещи, над которыми ещё стоит работать:
- именование переменных и функций

Новые идеи:
- работа с файлами
- абсолютные и относительные пути
- манипуляция файловыми путями
- кодирование строк на коленке
- drop-in replacement
- Саша может ошибаться :)

Так держать!
