### ISSUE TITLE
Написать функцию добычи подробностей о фильме

### ISSUE THREAD

**Issue by Suor** [dariyagrishina/kind-of-graduation-project#7]
Требуется написать функцию добычи информации о фильме. Результатом должен быть словарь, содержащий:
- название
- год
- описание
- продолжительность в минутах
- жанр

``` python
>>> get_info(13)
{'title': 'Матрица', 'year': 1998, ...}
```

**Comment by dariyagrishina** [comment]
У простой задачи возникли сложности с кодировкой. У меня в словаре вылезает вот такое {'title': '\xd0\x92\xd0\xb5\xd0\xb4\xd1\x8c\xd0\xbc\xd0\xb0 \xd0\xb8\xd0\xb7 \xd0\x91\xd0\xbb\xd1\x8d\xd1\x80: \xd0\x9a\xd1\x83\xd1\x80\xd1\x81\xd0\xbe\xd0\xb2\xd0\xb0\xd1\x8f \xd1\x81 \xd1\x82\xd0\xbe\xd0\xb3\xd0\xbe \xd1\x81\xd0\xb2\xd0\xb5\xd1\x82\xd0\xb0'}.
Как я с этим боролась: 1) выяснила, что из себя представляет вот этот value функцией type().
Это unicode, Решила, что раз это юникод - значит, его нужно превратить в нормальную строку. Делала я это путем .encode('utf8'). Строкой-то оно стало, но отображаться лучше не стало. 
Я уже психую, пыталась разными способами, читала stackoverflow. Не получается, планирую вернуться после семинара вечером и снова все внимательно прочитать и обдумать.
АААААААААРРРРР!

**Comment by Suor** [comment]
Если оно в начале отображалось как u'\u0432\u0543...', то так и должно
быть. Ты делаешь функцию, а не готовую программу, и она должна возвращать
строки в логическом (Unicode) формате. Считай, что ты прошла посвящение ;-)

**Comment by dariyagrishina** [comment]
Если быть точнее, то u'\u0412\u0435...' :)
Давай тогда я допишу этот get_info в том виде, в котором у меня это выходит, а ты потом мне расскажешь подробнее, что с этим делать? )

**Comment by Suor** [comment]
Ок

**Comment by dariyagrishina** [comment]
Смотри. Если я прошу программу выдать мне словарь, у меня получается {'title': 'Матрица', 'year': 1998, ...}, но в юникоде. Мы считаем это за выполнение поставленной задачи?
Если да, то могу поужинать, подчистить и запушить :)

**Comment by Suor** [comment]
Задача была написать функцию, а не программу )

**Comment by dariyagrishina** [comment]
Аааааа, функцию-функцию. А в чем отличие? Чем функция не программа?

**Comment by dariyagrishina** [comment]
Руки, ноги... Главное - хвост!

**Comment by Suor** [comment]
Программа может выдать только текст, а функция произвольную структуру.

**Comment by dariyagrishina** [comment]
Смотри :)

**Comment by Suor** [comment]
Кроме ревью в комментах есть ещё замечания:
- нужно было написать функцию, а не программу,
- не нужно ломать старое, когда пишешь новое, 
  если старое не нужно, то следует удалить его отдельным коммитом с пояснениями.
- не был выбран формат данных, всё возвращается просто строками. 

Остановимся на последнем моменте. В задаче не было описано, что в точности должна возвращать функция. В таком случае ты проектируешь сама, исходя из здравого смысла. Например, год - число, жанры - список строк.

**Comment by dariyagrishina** [comment]
1.Нужно ли мне исправить и сделать так, чтобы это была только функция?
2. Подожди-подожди! У меня жанр - строка, а не список строк. Список строк - это вместе с html.

**Comment by Suor** [comment]
1. Ага.
2. Жанров не у тебя, а у фильма несколько, просто ты их сейчас возвращаешь в виде строки соединёнными через `", "`.

**Comment by dariyagrishina** [comment]
1. Так и оставить, как оно сейчас есть?

**Comment by dariyagrishina** [comment]
Сволочь! Он автоматически мою двойку на единицу исправляет!
