### ISSUE TITLE
Сделать простенькую HTML-страницу

### ISSUE THREAD

**Issue by Suor** [dariyagrishina/kind-of-graduation-project#8]
Страница должна быть собрана с помощью фреймворка Bootstrap и содержать:
- верхнюю навигационную панель с названием проекта и парой других ссылок,
- строку поиска с кнопкой Go.

**Comment by dariyagrishina** [comment]
Задание выполнила. Страница содержит в себе и навигационную панель, и строку поиска с кнопкой Go. Но мне не нравится отсутствие какого-либо наполнения - текста, подсказывающего что нужно вводить (оставила на потом, поскольку пока сама не знаю, как будет все окончательно выглядеть и работать), еще каких-то вещей. Пока все очень скромно :)

**Comment by Suor** [comment]
Сделал ревью. Кроме того, что в файле: твоё должно быть чётко отделено от сторонних библиотек, чтобы например, их можно было обновить при надобности, исключить из поиска текстового редактора и т.п. Сейчас у твои файлики `index.html` и `starter-template.css` лежат в куче, кроме того последний неправильно называется.

Также взгляни на картинку:

![dasha-email-error](https://cloud.githubusercontent.com/assets/284103/6894109/78c62e04-d6f4-11e4-8623-0430b851dcbc.png)

**Comment by Suor** [comment]
Это пока не доделано?

**Comment by dariyagrishina** [comment]
Нет, не доделано.

**Comment by dariyagrishina** [comment]
Ты говоришь, что мои файлики лежат в куче. Что мне сделать. чтобы они не лежали в куче? Выделить папку для них?

**Comment by Suor** [comment]
Можно их просто наружу вытянуть пока, чтобы они не лежали в папке бутстрапа.

**Comment by Suor** [comment]
Подчистил - 404fd8af51d55f5a536a5181725ddd4623a6540a: поправил мета-теги и убрал ненужные комментарии.

**Comment by Suor** [comment]
Поправил строку поиска с использованием сетки и прицепной кнопки - https://github.com/dariyagrishina/kind-of-graduation-project/commit/497590ca8cf55a6fbe8c500abb23761be20f5dde.

Про сетку (grid) можно почитать [здесь](http://getbootstrap.com/css/#grid). Вкратце - бутстрап позволяет свои компоненты размещать в 12-и колоночной сетке, можно указывать ширины и отступы. Например:

``` html
<div class="row"> <!-- ряд -->
  <div class="col-lg-8 col-lg-offset-2"> <!-- ячейка -->
    <!-- вставляем что-то сюда, оно займёт 8 колонок и будет отбито 2 колонками слева, 
         т.е. центрировано -->
  </div>
</div>
```

Прицепные кнопки описаны [здесь](http://getbootstrap.com/components/#input-groups-buttons).

**Comment by Suor** [comment]
Дебрифинг.

Для веб-приложения html - это пользовательский интерфейс (UI). Ты вступила на эту зыбкую почву :)

Новые вещи:
- разделение своего и чужого кода
- использование html- фреймворка
- мета-теги
- особенности браузеров (в лёгкой версии)
- стили: внешние и инлайновые
- относительные единицы в CSS
- сетка

А казалось бы сделать одну маленькую страничку). Страничка покорена, Даша - молодец.
